
export enum QuestionType {
  MCQ = 'mcq',
  SHORT_ANSWER = 'short_answer',
  LONG_ANSWER = 'long_answer'
}

export interface Question {
  id: string;
  type: QuestionType;
  topic: string;
  text: string;
  options?: string[]; // Only for MCQ
  correctOptionIndex?: number; // Only for MCQ
  modelAnswer?: string; // Generated by AI for reference
}

export interface UserAnswer {
  questionId: string;
  answer: string | number; // index for MCQ, text for others
  score?: number; // 0-100
  feedback?: string;
  aiGraded?: boolean;
  modelAnswer?: string;
}

export interface QuizConfig {
  mcqCount: number;
  shortCount: number;
  longCount: number;
  difficulty: 'easy' | 'medium' | 'hard';
  focusTopics: string[]; // From previous weak areas
  selectedTopics: string[]; // Explicitly selected by user
}

export interface UserProfile {
  weakTopics: Record<string, number>; // Topic -> Count of mistakes
  totalQuizzes: number;
  averageScore: number;
}

export interface GradingResult {
  score: number;
  feedback: string;
  modelAnswer: string;
}
